### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by GheorgheP** [anthonynichols/node-include#5]
Is there any way to make it work properly with webpack?

When set in webpack config:

```js
node: {
	fs: 'empty'
}
```

I get this error: `Cannot find module "."` as users provide the relative path, in this case the current directory.

**Comment by anthonynichols** [comment]
Hi @GheorgheP 

You don't need to use this package if you are using Webpack. Webpack is able to do what this package solves: https://webpack.js.org/configuration/resolve/#resolve-modules

If you set up your Webpack config with something like this, you should be able to `import` or `require` modules relative to your root directory.

```json5
{  
  resolve: {
    modules: [
      path.resolve(__dirname)
    ]
  }
}
```
